force-app/main/default/objects/AcademicInterest/fields/Application_Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Application_Close_Date__c</fullName>
    <formula>AcademicTerm.LateRegistrationDate</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Application Close Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/AcademicInterest/fields/IsClosed__c.field-meta.xml
<CustomField>
    <fullName>IsClosed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsClosed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/dr_AcademicInterestBatch.cls
global class dr_AcademicInterestBatch implements DataBase.Batchable<sObject>{
    
    global DataBase.QueryLocator start(DataBase.BatchableContext bc){
        Date thisToday = Date.Today();
        Date reducedDate= thisToday.addDays(5);
        String recordToQuery = 
            'SELECT Id, Name, AccountId,Contact.Name, ContactId,Contact.Email, Status, Application_Close_Date__c, LearningProgramId, AcademicTermId,LearningProgram.Name ' +
            'FROM AcademicInterest ' +
            'WHERE IsClosed__c = false AND Application_Close_Date__c < :reducedDate And ContactId != NULL';
        
        return DataBase.getQueryLocator(recordToQuery);
    }
    
    global void execute(DataBase.BatchableContext bc, List<AcademicInterest> thisAcademicInterest){
        
        System.enqueueJob(new dr_QueuableAcademicInterest(thisAcademicInterest));
    }
    
    global void finish(DataBase.BatchableContext bc){
    }
}